// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: tools.proto

package emailservice

import (
	"context"

	"apitools/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	EmailAttachment = pb.EmailAttachment
	SendEmailReq    = pb.SendEmailReq
	SendEmailResp   = pb.SendEmailResp

	EmailService interface {
		// 发送邮件
		SendEmail(ctx context.Context, in *SendEmailReq, opts ...grpc.CallOption) (*SendEmailResp, error)
	}

	defaultEmailService struct {
		cli zrpc.Client
	}
)

func NewEmailService(cli zrpc.Client) EmailService {
	return &defaultEmailService{
		cli: cli,
	}
}

// 发送邮件
func (m *defaultEmailService) SendEmail(ctx context.Context, in *SendEmailReq, opts ...grpc.CallOption) (*SendEmailResp, error) {
	client := pb.NewEmailServiceClient(m.cli.Conn())
	return client.SendEmail(ctx, in, opts...)
}
