// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: tools.proto

package server

import (
	"context"

	"apitools/rpc/internal/logic"
	"apitools/rpc/internal/svc"
	"apitools/rpc/pb"
)

type EmailServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedEmailServiceServer
}

func NewEmailServiceServer(svcCtx *svc.ServiceContext) *EmailServiceServer {
	return &EmailServiceServer{
		svcCtx: svcCtx,
	}
}

// 发送邮件
func (s *EmailServiceServer) SendEmail(ctx context.Context, in *pb.SendEmailReq) (*pb.SendEmailResp, error) {
	l := logic.NewSendEmailLogic(ctx, s.svcCtx)
	return l.SendEmail(in)
}
