// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type EmailAttachment struct {
	FileName    string `json:"file_name"`
	Content     string `json:"content"`
	ContentType string `json:"content_type"`
	Size        int64  `json:"size,omitempty"`
}

type SendEmailReq struct {
	To          []string          `json:"to"`
	Cc          []string          `json:"cc,omitempty"`
	Bcc         []string          `json:"bcc,omitempty"`
	Subject     string            `json:"subject"`
	Content     string            `json:"content"`
	ContentType string            `json:"content_type,omitempty"`
	From        string            `json:"from,omitempty"`
	FromName    string            `json:"from_name,omitempty"`
	ReplyTo     string            `json:"reply_to,omitempty"`
	Priority    int               `json:"priority,omitempty"`
	Attachments []EmailAttachment `json:"attachments,omitempty"`
}

type SendEmailResp struct {
	Code     int64  `json:"code"`
	Message  string `json:"message"`
	EmailId  string `json:"email_id,omitempty"`
	SendTime int64  `json:"send_time,omitempty"`
}
