// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	email "apitools/api/internal/handler/email"
	work "apitools/api/internal/handler/work"
	"apitools/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/send",
				Handler: email.SendEmailHandler(serverCtx),
			},
		},
		rest.WithPrefix("/email"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/git_code_commit_record",
				Handler: work.GitCodeCommitRecordHandler(serverCtx),
			},
		},
		rest.WithPrefix("/work"),
	)
}
