// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: tools.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 邮件发送请求
type SendEmailReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 收件人列表（必填）
	To []string `protobuf:"bytes,1,rep,name=to,proto3" json:"to,omitempty"`
	// 抄送列表（可选）
	Cc []string `protobuf:"bytes,2,rep,name=cc,proto3" json:"cc,omitempty"`
	// 密送列表（可选）
	Bcc []string `protobuf:"bytes,3,rep,name=bcc,proto3" json:"bcc,omitempty"`
	// 邮件主题（必填）
	Subject string `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	// 邮件正文内容（必填）
	Content string `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	// 内容类型，如 "text/plain" 或 "text/html"（可选，默认为 text/plain）
	ContentType string `protobuf:"bytes,6,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	// 发件人邮箱（可选，通常由系统配置）
	From string `protobuf:"bytes,7,opt,name=from,proto3" json:"from,omitempty"`
	// 发件人显示名称（可选）
	FromName string `protobuf:"bytes,8,opt,name=from_name,json=fromName,proto3" json:"from_name,omitempty"`
	// 回复邮箱（可选）
	ReplyTo string `protobuf:"bytes,9,opt,name=reply_to,json=replyTo,proto3" json:"reply_to,omitempty"`
	// 邮件优先级：1-高，3-普通，5-低（可选）
	Priority int32 `protobuf:"varint,10,opt,name=priority,proto3" json:"priority,omitempty"`
	// 附件列表（可选）
	Attachments   []*EmailAttachment `protobuf:"bytes,11,rep,name=attachments,proto3" json:"attachments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailReq) Reset() {
	*x = SendEmailReq{}
	mi := &file_tools_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailReq) ProtoMessage() {}

func (x *SendEmailReq) ProtoReflect() protoreflect.Message {
	mi := &file_tools_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailReq.ProtoReflect.Descriptor instead.
func (*SendEmailReq) Descriptor() ([]byte, []int) {
	return file_tools_proto_rawDescGZIP(), []int{0}
}

func (x *SendEmailReq) GetTo() []string {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *SendEmailReq) GetCc() []string {
	if x != nil {
		return x.Cc
	}
	return nil
}

func (x *SendEmailReq) GetBcc() []string {
	if x != nil {
		return x.Bcc
	}
	return nil
}

func (x *SendEmailReq) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendEmailReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendEmailReq) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *SendEmailReq) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *SendEmailReq) GetFromName() string {
	if x != nil {
		return x.FromName
	}
	return ""
}

func (x *SendEmailReq) GetReplyTo() string {
	if x != nil {
		return x.ReplyTo
	}
	return ""
}

func (x *SendEmailReq) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *SendEmailReq) GetAttachments() []*EmailAttachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

// 邮件附件结构
type EmailAttachment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 附件文件名
	FileName string `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	// 附件内容（Base64编码）
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// 附件MIME类型
	ContentType string `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	// 附件大小（字节）
	Size          int64 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailAttachment) Reset() {
	*x = EmailAttachment{}
	mi := &file_tools_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailAttachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailAttachment) ProtoMessage() {}

func (x *EmailAttachment) ProtoReflect() protoreflect.Message {
	mi := &file_tools_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailAttachment.ProtoReflect.Descriptor instead.
func (*EmailAttachment) Descriptor() ([]byte, []int) {
	return file_tools_proto_rawDescGZIP(), []int{1}
}

func (x *EmailAttachment) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *EmailAttachment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *EmailAttachment) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *EmailAttachment) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// 邮件发送响应
type SendEmailResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 响应状态码
	Code int64 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// 响应消息
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// 邮件ID（发送成功时返回）
	EmailId string `protobuf:"bytes,3,opt,name=email_id,json=emailId,proto3" json:"email_id,omitempty"`
	// 发送时间戳
	SendTime      int64 `protobuf:"varint,4,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailResp) Reset() {
	*x = SendEmailResp{}
	mi := &file_tools_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailResp) ProtoMessage() {}

func (x *SendEmailResp) ProtoReflect() protoreflect.Message {
	mi := &file_tools_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailResp.ProtoReflect.Descriptor instead.
func (*SendEmailResp) Descriptor() ([]byte, []int) {
	return file_tools_proto_rawDescGZIP(), []int{2}
}

func (x *SendEmailResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SendEmailResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendEmailResp) GetEmailId() string {
	if x != nil {
		return x.EmailId
	}
	return ""
}

func (x *SendEmailResp) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

var File_tools_proto protoreflect.FileDescriptor

const file_tools_proto_rawDesc = "" +
	"\n" +
	"\vtools.proto\x12\x05tools\"\xb9\x02\n" +
	"\fSendEmailReq\x12\x0e\n" +
	"\x02to\x18\x01 \x03(\tR\x02to\x12\x0e\n" +
	"\x02cc\x18\x02 \x03(\tR\x02cc\x12\x10\n" +
	"\x03bcc\x18\x03 \x03(\tR\x03bcc\x12\x18\n" +
	"\asubject\x18\x04 \x01(\tR\asubject\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12!\n" +
	"\fcontent_type\x18\x06 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04from\x18\a \x01(\tR\x04from\x12\x1b\n" +
	"\tfrom_name\x18\b \x01(\tR\bfromName\x12\x19\n" +
	"\breply_to\x18\t \x01(\tR\areplyTo\x12\x1a\n" +
	"\bpriority\x18\n" +
	" \x01(\x05R\bpriority\x128\n" +
	"\vattachments\x18\v \x03(\v2\x16.tools.EmailAttachmentR\vattachments\"\x7f\n" +
	"\x0fEmailAttachment\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\"u\n" +
	"\rSendEmailResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\bemail_id\x18\x03 \x01(\tR\aemailId\x12\x1b\n" +
	"\tsend_time\x18\x04 \x01(\x03R\bsendTime2F\n" +
	"\fEmailService\x126\n" +
	"\tSendEmail\x12\x13.tools.SendEmailReq\x1a\x14.tools.SendEmailRespB\x06Z\x04./pbb\x06proto3"

var (
	file_tools_proto_rawDescOnce sync.Once
	file_tools_proto_rawDescData []byte
)

func file_tools_proto_rawDescGZIP() []byte {
	file_tools_proto_rawDescOnce.Do(func() {
		file_tools_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tools_proto_rawDesc), len(file_tools_proto_rawDesc)))
	})
	return file_tools_proto_rawDescData
}

var file_tools_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_tools_proto_goTypes = []any{
	(*SendEmailReq)(nil),    // 0: tools.SendEmailReq
	(*EmailAttachment)(nil), // 1: tools.EmailAttachment
	(*SendEmailResp)(nil),   // 2: tools.SendEmailResp
}
var file_tools_proto_depIdxs = []int32{
	1, // 0: tools.SendEmailReq.attachments:type_name -> tools.EmailAttachment
	0, // 1: tools.EmailService.SendEmail:input_type -> tools.SendEmailReq
	2, // 2: tools.EmailService.SendEmail:output_type -> tools.SendEmailResp
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tools_proto_init() }
func file_tools_proto_init() {
	if File_tools_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tools_proto_rawDesc), len(file_tools_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tools_proto_goTypes,
		DependencyIndexes: file_tools_proto_depIdxs,
		MessageInfos:      file_tools_proto_msgTypes,
	}.Build()
	File_tools_proto = out.File
	file_tools_proto_goTypes = nil
	file_tools_proto_depIdxs = nil
}
